name: ci

on:
  push:
    branches: [ 'main' ]
  pull_request:

concurrency:
  group: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}-ci
  cancel-in-progress: true

env:
  JRUBY_OPTS: '--debug -X+O -J-Xmn512m -J-Xms2048m -J-Xmx2048m -J-XX:-UseGCOverheadLimit'

jobs:
  main:
    name: ${{ matrix.os }}-${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
        ruby:
          - 'ruby-head'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - 'jruby-head'
          - 'jruby-9.3.2.0'
          - 'jruby-9.3.1.0'
          - 'jruby-9.3.0.0'
          - 'jruby-9.2.20.1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Code Climate test-reporter
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Install Dependencies
        run: |
          gem update --system 3.2.3
          gem install bundler
          bundle install --jobs 3 --retry 3

      - name: Run Tests
        run: bundle exec rake

      - name: Format Coverage Report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          GIT_BRANCH: ${{ github.event_name == 'pull_request' && github.head_ref || 'main' }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: |
          mkdir -p coverage-artifacts
          ./cc-test-reporter format-coverage coverage/coverage.json --input-type simplecov --output coverage-artifacts/ruby-${{ matrix.ruby }}-coverage.json

      - name: Save Coverage Report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: ruby-${{ matrix.ruby }}-coverage.json
          path: coverage-artifacts/ruby-${{ matrix.ruby }}-coverage.json
          retention-days: 1

  coverage:
    needs: [ 'main' ]
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Download Coverage Reports
        uses: actions/download-artifact@v2
        with:
          path: coverage-artifacts-temp

      - name: Finalize Artifacts
        run: |
          mkdir -p coverage-artifacts
          find coverage-artifacts-temp -mindepth 2 -type f -exec mv -i '{}' coverage-artifacts ';'

      - name: Upload Coverage
        env:
          GIT_BRANCH: ${{ github.event_name == 'pull_request' && github.head_ref || 'main' }}
          GIT_COMMIT_SHA: ${{ github.sha }}
          CC_TEST_REPORTER_ID: "23d80ff322cb6f334d19fd049df07430140bc2c9eb9567711a17387a5378f9c1"
        run: |
          ./cc-test-reporter sum-coverage coverage-artifacts/ruby-*-coverage.json --parts 11 --output coverage-artifacts/coverage.json
          ./cc-test-reporter upload-coverage --input coverage-artifacts/coverage.json
