name: ci

on:
  push:
    branches: [ 'main' ]
  pull_request:

concurrency:
  group: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}-ci
  cancel-in-progress: true

env:
  JRUBY_OPTS: '--debug -X+O -J-Xmn512m -J-Xms2048m -J-Xmx2048m -J-XX:-UseGCOverheadLimit'

jobs:
  main:
    name: ${{ matrix.os }}-${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
        ruby:
          - 'ruby-head'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - 'jruby-head'
          - 'jruby-9.3.2.0'
          - 'jruby-9.3.1.0'
          - 'jruby-9.3.0.0'
          - 'jruby-9.2.20.1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Dependencies
        run: |
          gem update --system 3.2.3
          gem install bundler
          bundle install --jobs 3 --retry 3

      - name: Run Tests
        run: bundle exec rake
